### PR TITLE
Fix for issue #30

### PR DESCRIPTION
**Pull request by MarioVilas**
This is a pull request with a fix for issue #30.

### CODE REVIEW

**Comment by h3xstream** [comment]
I'll try to test next weekend.

**Comment by h3xstream** [comment]
Sorry for the delay. I will look at the PR asap.

**Comment by h3xstream** [comment]
Update for the Bapp store was requested. It should update automatically your plugin soon.

**Comment by franklinyu** [comment]
I see that the commit has been merged to https://github.com/PortSwigger/retire-js, but still not available on BApp Store?

**Comment by franklinyu** [comment]
@pajswigger Any news?

**Comment by pajswigger** [comment]
Sorry, I didn't realize you were waiting on me. You are updated now.

**Pull request merged**
